### ISSUE TITLE
DOC: Installation instructions for utilizing Anaconda

### ISSUE THREAD

**Issue by Ananderz** [su77ungr/CASALIOY#113]
### Issue with current documentation:

Some of the commands in the instructions does not support Conda.

### Idea or request for content:

Anyone that have figured out how to set up using conda would make a lot of sense!

**Comment by bp020108** [comment]
i am trying same but not able to install casalioy module.  Do you have any luck? not sure it is due to version problem?

(cas)XX:~/CASALIOY/CASALIOY$ python3.11 casalioy/ingest.py
Traceback (most recent call last):
  File "/home/fabtool/CASALIOY/CASALIOY/casalioy/ingest.py", line 26, in <module>
    from load_env import chunk_overlap, chunk_size, documents_directory, get_embedding_model, ingest_n_threads, persist_directory
  File "/CASALIOY/CASALIOY/casalioy/load_env.py", line 9, in <module>
    from casalioy.utils import download_if_repo
ModuleNotFoundError: No module named 'casalioy'
(cas) :~/CASALIOY/CASALIOY$ pip3.11 install casalioy
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement casalioy (from versions: none)
ERROR: No matching distribution found for casalioy

[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: python3.11 -m pip install --upgrade pip
(cas) XX:~/CASALIOY/CASALIOY$

**Comment by abcnow** [comment]
Hey @bp020108 and @Ananderz .. you should take a look at this video.. it should fix the problems with Visual Studio Code and Python
---
https://www.youtube.com/watch?v=GqTsFOtZiQI
---
if you still want to go ahead and do it with Conda and "requirements.txt" here is the file -just create a file at the root level called: "requirements.txt" and copy and paste the following:

```
aiofiles==23.2.1 
aiohttp==3.8.5 
aiosignal==1.3.1 
async-timeout==4.0.3
attrs==23.1.0
beautifulsoup4==4.12.2
certifi==2023.7.22
cffi==1.16.0
charset-normalizer==3.3.0 
cryptography==41.0.4
filelock==3.12.4
frozenlist==1.4.0
langchain==0.0.267
libgenesis==0.1.9 
lxml==4.9.3
multidict==6.0.4
pdfminer-six==20221105
prompt-toolkit==3.0.39 
pycparser==2.21 
python-dotenv==1.0.0
qdrant-client==1.6.3 
requests-file==1.5.1 
requests==2.31.0 
sentencepiece==0.1.99 
six==1.16.0 
soupsieve==2.5 
tldextract==3.6.0 
urllib3==1.26.17 
wcwidth==0.2.8 
yarl==1.9.2 

```
erase the "poetry.lock and the "pypoetry.toml" and then follow these commands:

1. conda create --prefix ./conda_env python=3.10.0      (it will create an environment folder called "conda_env" with python version 3.10.0)
2. 
<img width="1079" alt="image" src="https://github.com/su77ungr/CASALIOY/assets/35501607/7befe89a-f559-4110-8ba8-47b12c93a344">

once you activate your environment.. and it tells you the command you should use for that in the command line console...then

3. pip install -r requirements.txt

**if after these steps some of the modules tell you that they could not be resolved then inside Visual Studio Code enter 

"Shift-Cmd + P" 
         and click on Select Interpreter (usually is the one that has "base" next to it.. but you can play with each oen of them)

---> you should be ready to start ingesting the files
