### ISSUE TITLE
ValueError: Collection test not found (after "Enter a query:" prompt)

### ISSUE THREAD

**Issue by hisxo** [su77ungr/CASALIOY#16]
Hello,

Since the last update of your repo, I'm faced with an error when the script ask to enter a query:

```
root@scw-boring-herschel:~/CASALIOY# python3 startLLM.py
llama.cpp: loading model from ./models/ggml-model-q4_0.bin
llama.cpp: can't use mmap because tensors are not aligned; convert to new format to avoid this
llama_model_load_internal: format     = 'ggml' (old version with low tokenizer quality and no mmap support)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 512
llama_model_load_internal: n_embd     = 4096
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 32
llama_model_load_internal: n_layer    = 32
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 2 (mostly Q4_0)
llama_model_load_internal: n_ff       = 11008
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 7B
llama_model_load_internal: ggml ctx size = 4113748.20 KB
llama_model_load_internal: mem required  = 5809.33 MB (+ 2052.00 MB per state)
...................................................................................................
.
llama_init_from_file: kv self size  =  512.00 MB
AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 |
gptj_model_load: loading model from './models/ggml-gpt4all-j-v1.3-groovy.bin' - please wait ...
gptj_model_load: n_vocab = 50400
gptj_model_load: n_ctx   = 2048
gptj_model_load: n_embd  = 4096
gptj_model_load: n_head  = 16
gptj_model_load: n_layer = 28
gptj_model_load: n_rot   = 64
gptj_model_load: f16     = 2
gptj_model_load: ggml ctx size = 4505.45 MB
gptj_model_load: memory_size =   896.00 MB, n_mem = 57344
gptj_model_load: ................................... done
gptj_model_load: model size =  3609.38 MB / num tensors = 285

Enter a query: hello

llama_print_timings:        load time =   162.28 ms
llama_print_timings:      sample time =     0.00 ms /     1 runs   (    0.00 ms per run)
llama_print_timings: prompt eval time =   161.97 ms /     2 tokens (   80.99 ms per token)
llama_print_timings:        eval time =     0.00 ms /     1 runs   (    0.00 ms per run)
llama_print_timings:       total time =   164.73 ms
Traceback (most recent call last):
  File "/root/CASALIOY/startLLM.py", line 49, in <module>
    main()
  File "/root/CASALIOY/startLLM.py", line 34, in main
    res = qa(query)
  File "/usr/local/lib/python3.9/dist-packages/langchain/chains/base.py", line 140, in __call__
    raise e
  File "/usr/local/lib/python3.9/dist-packages/langchain/chains/base.py", line 134, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/usr/local/lib/python3.9/dist-packages/langchain/chains/retrieval_qa/base.py", line 119, in _call
    docs = self._get_docs(question)
  File "/usr/local/lib/python3.9/dist-packages/langchain/chains/retrieval_qa/base.py", line 181, in _get_docs
    return self.retriever.get_relevant_documents(question)
  File "/usr/local/lib/python3.9/dist-packages/langchain/vectorstores/base.py", line 375, in get_relevant_documents
    docs = self.vectorstore.max_marginal_relevance_search(
  File "/usr/local/lib/python3.9/dist-packages/langchain/vectorstores/qdrant.py", line 273, in max_marginal_relevance_search
    results = self.client.search(
  File "/usr/local/lib/python3.9/dist-packages/qdrant_client/qdrant_client.py", line 277, in search
    return self._client.search(
  File "/usr/local/lib/python3.9/dist-packages/qdrant_client/local/qdrant_local.py", line 140, in search
    collection = self._get_collection(collection_name)
  File "/usr/local/lib/python3.9/dist-packages/qdrant_client/local/qdrant_local.py", line 102, in _get_collection
    raise ValueError(f"Collection {collection_name} not found")
ValueError: Collection test not found
```

Thanks!

Regards,
Hisxo

**Comment by su77ungr** [comment]
Thanks, 
good catch.
[this](https://github.com/su77ungr/CASALIOY/commit/001f2952d85df2f8885202eca4048fd5ed577ac2) should fix it.

**Comment by alxspiker** [comment]
Also got this error when I didn't let an ingest complete (So I guess no vector store was created), maybe there should be a try catch that if there is no collection named 'test' it prints that there was no database found and you have to make a database first by running the ingest script.
