### ISSUE TITLE
ModuleNotFoundError: No module named 'streamlit.proto.BackMsg_pb2' when running 'streamlit run .\gui.py'

### ISSUE THREAD

**Issue by atxcowboy** [su77ungr/CASALIOY#39]
Do you guys get any sleep? Your work is incredible!

On the current codebase, I get:

streamlit run .\gui.py
Traceback (most recent call last):
  File "C:\Users\Sasch\.conda\envs\casalioy\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Sasch\.conda\envs\casalioy\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Sasch\.conda\envs\casalioy\Scripts\streamlit.exe\__main__.py", line 4, in <module>
  File "C:\Users\Sasch\.conda\envs\casalioy\lib\site-packages\streamlit\__init__.py", line 55, in <module>
    from streamlit.delta_generator import DeltaGenerator as _DeltaGenerator
  File "C:\Users\Sasch\.conda\envs\casalioy\lib\site-packages\streamlit\delta_generator.py", line 36, in <module>
    from streamlit import config, cursor, env_util, logger, runtime, type_util, util
  File "C:\Users\Sasch\.conda\envs\casalioy\lib\site-packages\streamlit\cursor.py", line 18, in <module>
    from streamlit.runtime.scriptrunner import get_script_run_ctx
  File "C:\Users\Sasch\.conda\envs\casalioy\lib\site-packages\streamlit\runtime\__init__.py", line 16, in <module>
    from streamlit.runtime.runtime import Runtime as Runtime
  File "C:\Users\Sasch\.conda\envs\casalioy\lib\site-packages\streamlit\runtime\runtime.py", line 29, in <module>
    from streamlit.proto.BackMsg_pb2 import BackMsg
ModuleNotFoundError: No module named 'streamlit.proto.BackMsg_pb2'

**Comment by hippalectryon-0** [comment]
Fixed in #40
